esphome:
  name: cyd-monitor
  friendly_name: CYD-Monitor

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: '3.1'
  
packages:
  common-base: !include common/common-esp.yaml

web_server:
  port: 80
  version: 3
  ota: false

font:
  - file:
      type: gfonts
      family: Roboto
    id: roboto_large
    size: 40
    bpp: 4

globals:
  - id: touch_x
    type: int
    initial_value: '0'
  - id: touch_y
    type: int
    initial_value: '0'

time:
  - platform: homeassistant
    id: sntp_time

spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin:
      number: GPIO12
      ignore_strapping_warning: true

  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

output:
  - id: backlight_pwm
    platform: ledc
    pin: GPIO21

  - id: output_red
    platform: ledc
    pin: GPIO22
    inverted: true

  - id: output_green
    platform: ledc
    pin: GPIO16
    inverted: true

  - id: output_blue
    platform: ledc
    pin: GPIO17
    inverted: true

light:
  - id: backlight
    name: Display Backlight
    platform: monochromatic
    output: backlight_pwm
    restore_mode: ALWAYS_ON

  - id: led
    name: RGB Backlight 
    platform: rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

display:
  - id: main_display
    platform: ili9xxx
    model: ILI9341
    spi_id: tft
    data_rate: 40MHz
    cs_pin:
      number: GPIO15
      ignore_strapping_warning: true
    dc_pin:
      number: GPIO2
      ignore_strapping_warning: true
    dimensions:
      width: 240
      height: 320
    color_palette: 8BIT
    invert_colors: false
    rotation: 90
    update_interval: never
    auto_clear_enabled: false
    show_test_card: false

touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    threshold: 400
    calibration:
      x_min: 236
      x_max: 3801
      y_min: 168
      y_max: 3744
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false
    on_touch:
      then:
        - lvgl.label.update:
            id: coords
            text: !lambda |-
              char buf[32];
              sprintf(buf, "%d,%d", touch.x, touch.y);
              return std::string(buf);
        - lvgl.obj.update:
            id: touch_circle
            x: !lambda 'return touch.x - 10;'
            y: !lambda 'return touch.y - 10;'
lvgl:
  buffer_size: 25%
  draw_rounding: 2
  displays:
    - main_display
  touchscreens:
    - main_touchscreen
  widgets:
    - label:
        id: message
        text: "Hello World!"
        align: center
    - label:
        id: coords
        text: "0,0"
        align: bottom_mid
    - obj:
        id: touch_circle
        width: 20
        height: 20
        align: top_left
        x: 0
        y: 0
        radius: 10
        bg_color: 0xFF0000
        bg_opa: COVER
