esphome:
  name: minimonitor
  friendly_name: MiniMonitor

  on_boot:
      - priority: -100
        then:
          - light.turn_on:
              id: backlight
              brightness: 40%
      - then:
        - script.execute: update_screen
        - delay: 3s
        - lambda: id(boot_mode) = false;

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  common-base: !include common/common.yaml

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

web_server:
  port: 80
  version: 3
  ota: false

<<: !include minimonitor/theme.yaml
<<: !include minimonitor/sensor.yaml
<<: !include minimonitor/page_handler.yaml

time:
  - platform: homeassistant
    id: sntp_time

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  interface: hardware
  id: spihwd

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO21

light:
  - platform: monochromatic
    id: backlight
    name: "Backlight"
    output: backlight_output

image:
  rgb565:
    - file: "images/angry_unicorn.png"
      id: angry_unicorn
      resize: 240x240

display:
  - platform: st7789v
    model: Custom
    id: screen
    dc_pin: GPIO17
    reset_pin: GPIO4
    spi_id: spihwd
    rotation: 0
    width: 240
    height: 240
    offset_height: 0
    offset_width: 0
    update_interval: never
    spi_mode: mode3
    lambda: !include minimonitor/display_lambda.yaml
