esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  #min_version: 2024.6.0
  #name_add_mac_suffix: false
  #includes:
  #  - ./smart-mood-light/diyhueasyncudp-generic.h

bk72xx:
  board: generic-bk7231n-qfn32-tuya

<<: !include common-bk.yaml

logger:
  level: INFO
  baud_rate: 0

#custom_component:
#- lambda: |-
#    auto diyhue = new diyhueudp();
#    return {diyhue};

# web_server:
#   port: 80
#   version: 3
#   ota: false

# mdns:
#   services:
#     - service: "_entertainment"
#       protocol: "_udp"
#       port: 2100
#       txt:
#         friendly_name: ${friendly_name}

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version
  # - platform: wifi_info
  #   ip_address:
  #     name: ESP IP Address
  # - platform: template
  #   name: "light_id"
  #   id: light_id
  #   lambda: |-
  #     char response[100];
  #     memset( response, 0, 100 );
  #     strcat( response, "esphome_diyhue_light;");
  #     strcat( response, WiFi.macAddress().c_str());
  #     strcat( response, ";");
  #     strcat( response, App.get_name().c_str());
  #     strcat( response, ";0;0" ); // ;CT_BOOST;RGB_BOOST values go here; Replace with 0 to disable
  #     return { response };
  #   update_interval: 24h

# switch:
#   - platform: template
#     name: entertainment_switch
#     id: entertainment_switch
#     optimistic: true
#     lambda: return id(entertainment_switch).state;

globals:
- id: effect_index
  type: int
  initial_value: "0"
- id: color_index
  type: int
  initial_value: "0"
- id: colors
  type: float[12]
  initial_value: "{1., 1., 1., .5, .0, .0, .0, .0, .0, .5, 1., 1.}"
- id: brightness_backup
  type: float
  initial_value: ".0"

binary_sensor:
  - platform: gpio
    id: binary_toggle_light
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: color_led
        # if:
        #   condition:
        #     - light.is_on: color_led
        #   then:
        #     - lambda: |-
        #         if(id(color_led).remote_values.get_color_mode() == light::ColorMode::RGB)
        #         {
        #           auto call = id(color_led).turn_on();
        #           call.set_color_mode(light::ColorMode::WHITE);
        #           call.set_transition_length(1000);
        #           call.perform();
        #         }
        #         else{
        #           id(color_led).turn_off().set_transition_length(1000).perform();
        #         }
        #         return;
        #   else:
        #     - light.turn_on: color_led

  - platform: gpio
    id: binary_cycle_effects
    pin:
      number: P9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        if:
          condition:
            - light.is_on: color_led
          then:
            - lambda: |-
                std::string actual_effect = id(color_led).get_effect_name();
                static int total_effects = id(color_led).get_effects().size();
                std::string this_effect = "";

                if(actual_effect == "None") {
                  id(effect_index) = 0;
                } else {
                  for(int i = 0; i <= total_effects; i++) {
                    this_effect = id(color_led).get_effects().at(i)->get_name();
                    if (this_effect == actual_effect) {
                      id(effect_index) = i + 1;
                      break;
                    }
                  }

                  if (id(effect_index) == total_effects) {
                    id(effect_index) =- 1;
                  }
                }

                if (id(effect_index) == -1) {
                  id(color_led).turn_on().set_effect("None").perform();
                } else {
                  auto call = id(color_led).turn_on();
                  std::string effect = id(color_led).get_effects().at(id(effect_index))->get_name();
                  call.set_effect(effect.c_str());
                  call.perform();
                }
                return;

  - platform: gpio
    id: binary_cycle_colors
    pin:
      number: P8
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        if:
          condition:
            - light.is_on: color_led
          then:
            - lambda: |-
                auto call = id(color_led).turn_on();
                call.set_color_mode(light::ColorMode::RGB);
                call.set_transition_length(1000);
                int ridx = id(color_index);
                int gidx = ridx + 8 < 12 ? ridx + 8 : ridx - 4;
                int bidx = ridx + 4 < 12 ? ridx + 4 : ridx - 8;
                call.set_rgb(id(colors)[ridx], id(colors)[gidx], id(colors)[bidx]);
                call.perform();
                id(color_index) = id(color_index) < 12 ? id(color_index) + 1 : 0;
                return;

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P6
  - platform: libretiny_pwm
    id: output_green
    pin: P7
  - platform: libretiny_pwm
    id: output_blue
    pin: P24
  - platform: libretiny_pwm
    id: output_cold
    pin: P26

light:
  - platform: rgbw
    id: color_led
    name: "color_led"
    red: output_red
    green: output_green
    blue: output_blue
    white: output_cold
    color_interlock: true
    restore_mode: RESTORE_AND_OFF
    default_transition_length: 0.4s
    gamma_correct: 1
    # Init brightness on light turn on
    on_turn_on:
      then:
        - lambda: |-
            ESP_LOGD("LedRing", "Turn on");
            if(id(brightness_backup) > .0)
            {
              ESP_LOGD("LedRing", "Restore brightness to %f", id(brightness_backup));
              id(color_led).turn_on().set_brightness(id(brightness_backup)).perform();
              id(brightness_backup) = .0;
            }
            return;
    effects:
      - lambda:
          name: Color cycle
          update_interval: 5s
          lambda: |-
            static int state = 0;
            auto call = id(color_led).turn_on();
            if(initial_run)
            {
              call.set_color_mode(light::ColorMode::RGB);
            }
            call.set_transition_length(1000);
            int ridx = state;
            int gidx = ridx + 8 < 12 ? ridx + 8 : ridx - 4;
            int bidx = ridx + 4 < 12 ? ridx + 4 : ridx - 8;
            call.set_rgb(id(colors)[ridx], id(colors)[gidx], id(colors)[bidx]);
            call.perform();
            state = state < 11 ? state + 1 : 0;
            return;
      - random:
      - flicker:
      - pulse:
      - lambda:
          name: Sunrise
          update_interval: 0.2s
          lambda: |-
            auto call = id(color_led).turn_on();
            static const unsigned long duration = 30 * 60; // in seconds
            static const float Imax = 0.9;
            static unsigned long timestart = 0;
            static unsigned long timestop = 0;
            
            unsigned long now = millis();

            if(initial_run)
            {
              timestart = now;
              timestop = now + duration * 1000;

              ESP_LOGD("Sunrise", "Start sun rise");

              id(brightness_backup) = id(color_led).remote_values.get_brightness();
              //ESP_LOGD("Sunrise", "Brighness: %f", id(brightness_backup));

              call.set_color_mode(light::ColorMode::RGB);

              // Set brightness to min
              call.set_brightness(0.0001);
              call.set_rgb(1., 0., 0.);
              call.set_transition_length(0);
              
              call.perform();
            }

            if (now < timestop) {

              unsigned long t = (now - timestart) / 1000; // seconds
              float R = Imax * 1.0 / (1 + exp(-0.5 * 30 / duration * (t - duration * 0.55) ) );
              float G = Imax * 0.7 / (1 + exp(-0.55 * 30 / duration * (t - duration * 0.7 ) ) );
              float B = Imax * 0.1 / (1 + exp(-0.6 * 30 / duration * (t - duration * 0.8 ) ) );
              float brightness = R > G ? (R > B ? R : B) : (G > B ? G : B);

              ESP_LOGD("Sunrise", "R: %f", R);

              call.set_transition_length(0);
              call.set_rgb(R, G, B);
              call.set_brightness(brightness);
              call.perform();
            }
            else
            {
              if (timestop > 0)
              {
                ESP_LOGD("Sunrise", "End sun rise");
                timestop = 0;
              }
            }

            return;
