esphome:
  name: !remove

api:
  encryption:
    key: !secret api_key

logger:

ota:
  - platform: esphome
    password: !secret ota_password

captive_portal:

mdns:

sensor:
  - platform: uptime
    name: Uptime
