esphome:
  name: !remove

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fallback ${friendly_name}"
    password: !secret fallback_password

api:
  encryption:
    key: !secret api_key

logger:

ota:
  - platform: esphome
    password: !secret ota_password

captive_portal:

mdns:

sensor:
  - platform: uptime
    name: Uptime
